include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    overridden_fields: ignore

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
