name: tekio_forms
description: "This package allows you to build a complex forms with just a json file. This package is a part of the tekio plugins."
version: 0.1.0
homepage: https://github.com/tekioplugins/tekio_forms
repository: https://github.com/tekioplugins/tekio_forms

topics: 
  - json
  - widget
  - dynamic
  - forms
  - validators

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  json_annotation: ^4.9.0
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pull_request_coverage: ^2.1.3
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
      - test/test_util_data/test_form_json/json_form_data_01.json
      - test/test_util_data/test_initial_json/json_initial_data_01.json

