name: tekio_forms
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  json_annotation: ^4.9.0
  flutter_form_builder: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pull_request_coverage: ^2.1.3
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
      - test/test_json_data/test_form_build_data/json_form_data_01.json
      - test/test_json_data/test_initial_values/json_initial_data_01.json

