//Test model to create documentation for the fields
// Can be used to continue the development of the fields
// this was majorly generated by chatgpt

class FieldsDataModel {
  String fieldKey;
  String fieldType;
  String fieldLabel;
  bool? isRequired;
  int? minLength;
  int? maxLength;

  FieldsDataModel({
    required this.fieldKey,
    required this.fieldType,
    required this.fieldLabel,
    this.isRequired,
    this.minLength,
    this.maxLength,
  });
}
