//Test model to create documentation for the fields
// Can be used to continue the development of the fields
// this was majorly generated by chatgpt

import 'package:tekio_forms/models/form_field_enum.dart';

class FormFieldsModel {
  String fieldKey;
  TekioFieldEnum? fieldType;

  FormFieldsModel({required this.fieldKey, required this.fieldType});

  factory FormFieldsModel.fromJson(Map<String, dynamic> json) {
    return FormFieldsModel(
      fieldKey: json['fieldKey'],
      fieldType: TekioFieldEnum.fromJson(json['fieldType']),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'fieldKey': fieldKey,
      'fieldType': TekioFieldEnum.toJson(fieldType),
    };
  }
}
