//Test model to create documentation for the fields
// Can be used to continue the development of the fields
// this was majorly generated by chatgpt

import 'package:json_annotation/json_annotation.dart';
import 'package:tekio_forms/models/form_field_type.dart';

part '../generated/models/form_fields_data.g.dart';

@JsonSerializable()
class FormFieldsData {
  @JsonKey(name: 'fieldKey')
  String fieldKey;
  @JsonKey(name: 'fieldType')
  TekioFieldType? fieldType;
  @JsonKey(name: 'fieldLabel')
  String? fieldLabel;
  @JsonKey(name: 'fieldHint')
  String? fieldHint;
  @JsonKey(name: 'maxLines')
  int? maxLines;
  @JsonKey(name: 'minLines')
  int? minLines;
  @JsonKey(name: 'maxLength')
  int? maxLength;

  FormFieldsData({
    required this.fieldKey,
    required this.fieldType,
    this.fieldLabel,
    this.fieldHint,
    this.maxLines,
    this.minLines,
    this.maxLength,
  });

  factory FormFieldsData.fromJson(Map<String, dynamic> json) =>
      _$FormFieldsDataFromJson(json);

  Map<String, dynamic> toJson() => _$FormFieldsDataToJson(this);
}
