//Test model to create documentation for the fields
// Can be used to continue the development of the fields
// this was majorly generated by chatgpt

import 'package:tekio_forms/models/form_field_enum.dart';

class FormFieldsModel {
  String fieldKey;
  TekioFieldEnum? fieldType;
  String? fieldLabel;
  String? fieldHint;
  int? maxLines;
  int? minLines;
  int? maxLength;

  FormFieldsModel({
    required this.fieldKey,
    required this.fieldType,
    this.fieldLabel,
    this.fieldHint,
    this.maxLines,
    this.minLines,
    this.maxLength,
  });

  factory FormFieldsModel.fromJson(Map<String, dynamic> json) {
    return FormFieldsModel(
      fieldKey: json['fieldKey'],
      fieldType: TekioFieldEnum.fromJson(json['fieldType']),
      fieldLabel: json['fieldLabel'],
      fieldHint: json['fieldHint'],
      maxLines: json['maxLines'],
      minLines: json['minLines'],
      maxLength: json['maxLength'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'fieldKey': fieldKey,
      'fieldType': TekioFieldEnum.toJson(fieldType),
      'fieldLabel': fieldLabel,
      'fieldHint': fieldHint,
      'maxLines': maxLines,
      'minLines': minLines,
      'maxLength': maxLength,
    };
  }
}
